### ISSUE TITLE
오늘 번역할 부분을 정합시다!

### ISSUE THREAD

**Issue by ljhh-0611** [16-2-SKKU-OSS/16-2-OSS-C#7]
현재 번역 남아있는 부분중,

Configuring SSH ~ Update $HOME/.bashrc

Excursus: Hadoop Distributed File System (HDFS) ~ Stopping your single-node cluster

Running a MapReduce job

이렇게 job을 나눴으면 합니다! 어떠세요? 뭐 먼저 하고싶은게 있으시면 정하셔도 되구요!

오늘 끝내봅시다!

**Comment by YunJeon** [comment]
저 첫번째 부분 Configuring SSH ~ Update $HOME/.bashrc 하도록 하겠습니다!
그런데 그림 같은건 어떻게 올리나요??

**Comment by ljhh-0611** [comment]
그럼 제가 두번째를 할게요!

**Comment by ljhh-0611** [comment]
아 그리고 그림 올리는 방법도 md 파일 튜토리얼에 있습니다! 확인해보시면 되실듯해요~

**Comment by gw4621** [comment]
그럼 제가 세번째를 하지요

**Comment by kds135** [comment]
오잉 그럼 몇번째까지 남아있는건가요??? 3번째가 마지막인가요?? 저는 뭘 할 수 있는거죠??ㅠㅠ저번 수업때 졸작발표회때문에 빠져서 잘 모르겠네요ㅠㅠ

**Comment by YunJeon** [comment]
Hadoop이랑 Liscense 발표하신 분들은 발표자료 올리는거 하시면 되요~

**Comment by ljhh-0611** [comment]
현재 제 부분 번역해서 올렸습니다..!
아직 사진이라던가 좀 더 추가하고 수정할 사항이 많지만요!
